rack/rack

lib/rack/server.rb

Update to reflect changes in #514

Update to reflect changes in #514

---

lib/rack/head.rb

Fix indentation and move comment

Update head.rb Fix indentation and move comment

---

.travis.yml

http://docs.travis-ci.com/user/languages/ruby/#Default-Test-Script.

Use default bundle install command.

---

lib/rack/utils.rb

Script used: https://github.com/eileencodes/integration_performance_test/blob/master/test/integration/documents_allocations_create_test.rb

Reduce allocations

---

README.rdoc

This is a pull request created during an AirPair.
The goal is to understand how to submit to open source.
Apologize for the noise.
@snuggs, @zanadar

Place comma before and

---

test/spec_deflater.rb
test/spec_request.rb
test/spec_session_cookie.rb

Fix typos in test files

---

lib/rack.rb

Tiny little documentation change :smile:

Correct documentation at top of rack.rb about requiring it

---

lib/rack/request.rb

Choosed cleaner name for local variable

Better naming and fix for overwriting of Kernel#p

---

lib/rack.rb
lib/rack/auth/digest/request.rb
lib/rack/commonlogger.rb
lib/rack/handler/cgi.rb
lib/rack/handler/fastcgi.rb
lib/rack/handler/lsws.rb
lib/rack/handler/scgi.rb
lib/rack/handler/webrick.rb
lib/rack/lint.rb
lib/rack/lock.rb
lib/rack/logger.rb
lib/rack/methodoverride.rb
lib/rack/mock.rb
lib/rack/multipart/parser.rb
lib/rack/nulllogger.rb
lib/rack/recursive.rb
lib/rack/request.rb
lib/rack/sendfile.rb
lib/rack/session/abstract/id.rb
lib/rack/session/cookie.rb
lib/rack/session/memcache.rb
lib/rack/session/pool.rb
lib/rack/showexceptions.rb
lib/rack/showstatus.rb
lib/rack/tempfile_reaper.rb

Some of these variables was already constantized in the past. So this PR unifies the rest and move all these constants under one place (`lib/rack.rb`).

Constantize all rack environment variables and make them frozen

---

lib/rack/builder.rb

I think indent is wrong in document. so Fix it.

Fix indent in document

---

lib/rack/deflater.rb
lib/rack/sendfile.rb
lib/rack/session/memcache.rb
lib/rack/tempfile_reaper.rb

It's faster than calling a block
See: https://github.com/JuanitoFatas/fast-ruby#proc--block

Use a symbol proc instead of a block in some cases

---

lib/rack/handler/webrick.rb

Fix comment typing miss

---

SECURITY_POLICY.md

Signed-off-by: David Celis <me@davidcel.is>

Fix typo in Security Policy

---

lib/rack/multipart/parser.rb
test/multipart/unity3d_wwwform
test/spec_multipart.rb

Strip quotes from around multipart encodings

---

lib/rack/query_parser.rb
test/spec_utils.rb

These fixes would close quite a few issues. #951 and #1015 in rack, as well as several in rails.

Fixes 951 fixes 1015

---

HISTORY.md
lib/rack/utils.rb
test/spec_response.rb

Backports https://github.com/rack/rack/pull/980 and https://github.com/rack/rack/pull/1033 to the 1.6 branch.
/cc @jeremy @tenderlove

Backport SameSite cookie attribute

---

lib/rack/auth/digest/params.rb

```ruby
str = "realm=\"WallysWorld\", nonce=\"MTQ2MDAzNTE0OCA5M2VkNjk3ZGY1NzdjZDU1MjIxN2JlYjczYjY5ODFhYQ==\", opaque=\"b89b7aab1f82cfd3c770242e6ee42b16\", qop=\"auth\""
str.scan( /(\w+\=(?:"[^\"]+"|[^,]+))/n )
str.scan( /(\w+\=(?:"[^\"]+"|[^,]+))/n ).collect{ |v| v[0] }
```
Same as:
```ruby
str.scan(/\w+\=(?:"[^\"]+"|[^,]+)/n)
```

Micro refactor string scan in Rack::Auth::Digest::Params.split_header_value

---

.travis.yml

Just bump CI with last version of MRI Ruby.

Use last version of MRI Ruby with CI (travis)

---

lib/rack/request.rb

Move `Request#[]` and `Request#[]=` to `Helpers` and deprecate them

---

lib/rack/request.rb

Tried my best to migrate behavior to Helpers. Bit difficult since same
methods already exist there.
cc @tenderlove

Move Rack::Request convienence methods to Helpers

---

lib/rack/mock.rb

Ref: https://github.com/rack/rack/commit/812ac75b327c9f3d6ff5074def9721bf6f19e1de#commitcomment-425374

Remove unused variable.

---

lib/rack/file.rb
test/spec_file.rb

Update bytesize usage after its removal from rack utils

---

lib/rack/builder.rb
test/spec_builder.rb

Freezing the application and middleware instances can prevent
thread-safety issues at runtime.  This addresses the issues
discussed in #1010.
Unlike the solution proposed by #1010, this is backwards compatible
as it is opt-in, the application and middleware instances are
only frozen if you choose to use freeze_app.

Add Builder#freeze_app to freeze application and all middleware instances

---

lib/rack/lock.rb
test/spec_lock.rb

While the flow of environment information is generally downstream only, test frameworks sometimes rely on being able to pull information added to the environment after `.call`.
This can be seen
- In [rack-test](https://github.com/rack-test/rack-test/blob/fcfcd172fdfc0b5d9ca4cd27f8a5c8f68fbbecec/lib/rack/mock_session.rb#L32)
- In [Rails](https://github.com/rails/rails/blob/98f8f81879825a009b0c751b3178fcb687e3033a/actionpack/lib/action_dispatch/testing/integration.rb#L271) where the controller instance is pulled from the environment, which fails causing Rails/rails#29608 when `Rack::Lock` is being used.
~~In order to accomplish this, I had to change [a test](https://github.com/rack/rack/pull/1189/files#diff-6482bbd415bc6ca058c28b364a19aa7dR151), but this line was introduced in #828, (which …

Stop replacing the environment in Rack::Lock

---

lib/rack/multipart/parser.rb

fixes issue #1075 
The problem is that:
method `handle_mime_body` tries to check `@buf =~ rx` every time `@buf` is changed,
and `@buf =~ rx` is slow because it tries to seach `rx` from the beginning of `@buf` every time.
I changed `@buf =~ rx` to `@buf.index rx, appropriate_offset` to fix this.

Large file upload performance fix

---

lib/rack/multipart/parser.rb

When uploading a 512MB file, Rack consumes 549MB memory(more than the uploaded file size).
This pullreq will bump `@buf` to tempfile each time handle_mime_body is called, and reduce memory usage.
benchmark code: https://gist.github.com/tompng/54eb216d81c600a46fef28ddab68b356
549MB → 12MB when uploading 512MB file
```
{"file_size"=>1000000, "run_parser_called"=>1, "memory"=>"11MB"}
{"file_size"=>2000000, "run_parser_called"=>2, "memory"=>"12MB"}
{"file_size"=>4000000, "run_parser_called"=>4, "memory"=>"17MB"}
{"file_size"=>8000000, "run_parser_called"=>8, "memory"=>"21MB"}
{"file_size"=>16000000, "run_parser_called"=>16, "memory"=>"29MB"}
{"file_size"=>32000000, "run_parser_called"=>31, "memory"=>"46MB"}
{"file_size"=>64000000, "run_parser_called"=>62, "memory"=>"79MB"} …
```

Reduce memory usage when uploading large file

---

README.rdoc

Agoo is at https://github.com/ohler55/agoo. I believe it qualifies but a second opinion would be welcome.

Add Agoo web server to list on README.md

---

.circleci/config.yml

followup of https://github.com/zzak/rack/pull/2

DRY circleci.yml jobs

---

lib/rack/server.rb

I think it's time we bake in profiling tools in order to help people profile their app boot times.
This allows people to get boot-time profile information about their Rack
applications.  Integration in to `rackup` means that people can easily
profile not just *loading* code, but also the app compilation process
too.  This gives developers a more wholistic picture of application
boot-time performance because the webserver is given the *compiled*
application and compilation is a phase that is distinct from loading
code.
The profiler uses `stackprof`, so this patch adds a soft dependency on
`stackprof` for obtaining profile information.  Heap dumps use MRI's
built-in heap dumping capabilities.
Here is a simple example of using the wall time profiler:
```
[aaron@TC rack (boot-profile)]$ ruby …
```

Add boot-time profiling capabilities to `rackup`

---

lib/rack/multipart/generator.rb

Do not continue to traverse params instance variable after determining multipart is true.

More efficient multipart? method

---

SECURITY_POLICY.md

* Updated released versions ([link](https://rubygems.org/gems/rack/versions))
* Updated url for mailing list

[ci skip] Update SECURITY_POLICY.md

---

lib/rack/multipart/parser.rb

Passing a buffer string as a second argument to `IO#read` will make the Rack input IO, instead of creating a new string object on each read, load each chunk into the same string instance (overwriting the previous content). This greatly reduces string allocations.

Use buffer string when parsing multipart requests

---

README.rdoc

Change link in README.md to point to CHANGELOG.md instead of HISTORY.md (removed in 3524692)

CHANGELOG link fix

---

lib/rack/recursive.rb

I think this style is broken. so I fixed it.

Cosmetic change

---

lib/rack/builder.rb

This caused unexpected behaviour.
https://github.com/socketry/falcon/issues/33#issuecomment-436413100
When the user specified `falcon.rb` as the config file, it loaded code
from the gem rather than the local directory. This allows users to bypass
this "feature" by directly using `Builder.load_file` which doesn't try
to `require` the path.

Separate path loading from Builder.parse_file into Builder.load_file

---

lib/rack/handler.rb

* Server code is available here: https://github.com/socketry/falcon

Add falcon as an option by default.

---

lib/rack/utils.rb

This is defined in RFC 8297.
https://tools.ietf.org/html/rfc8297

Add status code: 103 Early Hints

---

lib/rack/file.rb
test/spec_static.rb

Expands the root path in Rack::Static upon initialization

---

lib/rack/chunked.rb
test/spec_chunked.rb

Trailer headers allow the sender to add additional information to a
chunked message.
An example message would look like this (taken from mozilla docs:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer)
```
HTTP/1.1 200 OK
Content-Type: text/plain
Transfer-Encoding: chunked
Trailer: Expires
7\r\n
Mozilla\r\n
9\r\n
Developer\r\n
7\r\n
Network\r\n
0\r\n
Expires: Wed, 21 Oct 2015 07:28:00 GMT\r\n
\r\n
```
This could be useful for sending an expiration but other trailer headers
as well like server timing.
While this works with cURL while implementing this we found that Chrome
doesn't support trailer headers (it seems like it might be supported for
HTTP/2 but I had trouble proving that). Once chrome does support trailer
headers we could implement server-timing and use the …

Add trailer headers to Rack

---

lib/rack/request.rb

This change reduces code duplication.

Replace `get_header HTTP_COOKIE` with `string`

---

lib/rack/request.rb

I found some unnecessary allocations especially in "forwarded_scheme" even if relevant headers aren't present
I tested it on a rails app, it saves about 100KB / 100 requests
performance is about 3% better (for the whole app)

reduce allocations in forwarded_scheme

---

lib/rack/static.rb
lib/rack/utils.rb

https://github.com/ruby/ruby/commit/2a22a6b2d8465934e75520a7fdcf522d50890caf
Regexp#match?(nil) raises an exception.
https://github.com/rails/rails/pull/37504

TypeError Regexp#match?(nil) in Ruby Head

---

lib/rack/query_parser.rb

This change focuses on making this single method a little bit less cryptic, and a little bit more performant.
In summary, the changed version:
- Adds documentation about what the method does together with a mutation warning. (Neither the old nor the new version is thread safe.)
- Adds an alias (`#to_h`) for the method that doesn't contain the redundant fragment.
- Flattens the conditional branches to make them easier to follow.
- Avoids allocating an array of strings for each params object.
- Improves performance by 12% for an average query string, and by 40% for an empty one. (Average of 5 runs with `benchmark-ips` using MRI 2.6.0.)
Feel free to pick and choose from the proposed changes.

Refactor QueryParser::Params#to_params_hash for readability and performance

---

README.rdoc

https://unit.nginx.org/configuration/#ruby

Add NGINX Unit web server to list on README.md

---

README.rdoc

While googling these projects I've also found that many of them are unmaintained for 10 years.

Added relevant links to the projects

---

lib/rack/multipart.rb
test/multipart/robust_field_separation
test/spec_multipart.rb

Robust separation of Content-Disposition fields

---

CHANGELOG.md

Add 2.0.8 and 1.6.12 to CHANGELOG

---

CHANGELOG.md

I've updated the Changelog with changes for the following commits: `git log 2-0-stable..master`

Add changes to Changelog

---

lib/rack/handler/webrick.rb
test/spec_server.rb

see https://github.com/rack/rack/issues/1013

fix SSLEnable for Webrick, see https://github.com/rack/rack/issues/1013

---

CHANGELOG.md

Changelog for 2.1.0

---

CHANGELOG.md
CONTRIBUTING.md
README.rdoc
rack.gemspec

This has been very useful in some of our other open-source projects, inviting other developers to contribute via clear guidelines. The following is inspired from [grape](https://github.com/intridea/grape) and is of course up for update regarding any Rack specifics.
Most of this is extracted from README.

Added CONTRIBUTING guidelines.

---

lib/rack/session/abstract/id.rb

reverts https://github.com/rack/rack/pull/1401
discussed in https://github.com/rack/rack/pull/1428

Revert #transform_keys

---

lib/rack/lint.rb
test/spec_lint.rb

This matches what is required by SPEC.
Fixes #1239

Make Rack::Lint check response is array with 3 elements

---

lib/rack/show_exceptions.rb
test/spec_show_exceptions.rb

Otherwise you get an exception trying to render the exception page.
Fixes #991

Make Rack::ShowExceptions handle invalid POST data

---

lib/rack/static.rb
test/spec_static.rb

This allows for handling missing files under a static path in a
custom manner.
Fixes #946

Support a :cascade option for Rack::Static

---

CHANGELOG.md

Fix typo in Padrino changelog entry

---

CHANGELOG.md
lib/rack/builder.rb
lib/rack/multipart/parser.rb
test/spec_builder.rb
test/spec_multipart.rb

Also update changelog for these and previously backported fixes.

Backport a couple important fixes to 2.1 stable

---

SPEC
lib/rack/lint.rb
test/spec_lint.rb

A frozen request env would break Rack::Request.

Require request env not be frozen in SPEC

---

lib/rack/response.rb

In response to https://github.com/rack/rack/pull/1434
I used yard style documentation but maybe it's wrong.
@jeremyevans @tenderlove what are your feelings on improving the documentation, e.g. using YARD style syntax, or sticking with RDoc (which I feel is a bit more clunky).

Document `Rack::Response#initialize` and `#finish`.

---

lib/rack/utils.rb
test/spec_response.rb

Also, correctly handle deleting with both a domain and path
provided.
Fixes #1234

Do more exact matching of domain and path when deleting cookies

---

lib/rack/response.rb

Follow up to feedback from https://github.com/rack/rack/pull/1517

Response documentation

---

CHANGELOG.md
lib/rack/utils.rb
test/spec_utils.rb

Sort encodings by server preference. Implements #1184.

---

lib/rack/deflater.rb

Explicit :sync => nil option is now treated as false instead of true.
We documented the default was true, but any explicit :sync option
should be respected.
gzip.write returns the length of the input string, so simplify the
GzipStream#each implementation by skipping all empty body strings.
Don't set @writer and @body to nil in GzipStream after using them.
We don't use this pattern in BodyProxy, so I don't see a need to
use it here.

Refactor and document Deflater

---

.rubocop.yml
test/spec_utils.rb

Ref https://github.com/rack/rack/pull/1549#discussion_r375470299, 1f89eaafd39040707bf2a76cab134dd7a78b1441.

Enable `Layout/Tab` to avoid hard tab indentation in the future

---

CHANGELOG.md
lib/rack.rb
lib/rack/request.rb
test/spec_request.rb

Fixes https://github.com/rack/rack/issues/1570

Remove SERVER_ADDR.

---

Rakefile

@jeremyevans what do you think about doing something like this?
I suggest we try to pull in a few more external gems, and then add that in the GitHub Actions tests, we can make a workflow just for external dependencies. It's a nice way add some higher level/extended extensive acceptance tests.

External gems

---

.github/workflows/development.yml

Test with truffleruby-head in CI

---

lib/rack/lint.rb
test/spec_lint.rb

Don't ary.inspect in the lint assertions

---

lib/rack/multipart/parser.rb

During refactoring, I also removed `#on_read` method. 
I'm wondering, am I allowed to do that? It seems for internal usage only.

Refactor Multipart::Parser parse loop logic

---

SPEC.rdoc

- This is the result of running 'rake spec'

Regenerate SPEC

---

CHANGELOG.md

Add 2.2.3 information to CHANGELOG

---

CHANGELOG.md
lib/rack/rewindable_input.rb
test/spec_rewindable_input.rb

to improve compatibility with fcgi

add size to Rack::RewindableInput

---

lib/rack/lint.rb

Fixes https://github.com/rack/rack/issues/1723

Fix inefficient assert pattern in Rack::Lint

---

CHANGELOG.md

Mark `ETag` change in 2.2.0 as breaking

---

lib/rack/deflater.rb

The current code in the method is below, and was added in [2008](https://github.com/rack/rack/commit/cabc20df5298), [2009](https://github.com/rack/rack/commit/c81542e28aa7) & [2011](https://github.com/rack/rack/commit/37d2b2fe4066).  When `@body` is a File object, `@body.each` is equivalent to `@body.gets`.  For a large 'text' file (css, js, html), this results in many iterations.
A lot has changed in the ten years, so added code to read the `@body` in 128kB chunks.  Old code is used if `@body` isn't a File object.
This results in a large speed increase.
Assuming that `@body.read` throws the same errors as `@body.each`, so no additional error handling is needed.
Note that `@body.is_a? ::File` is used for detection.  I'm not sure if `@body.is_a? ::IO` would be better...
```ruby
@body.each …
```

deflater.rb - optimize GzipStream#each

---

lib/rack/lint.rb

Lint content length

---

lib/rack/response.rb

The current implementation does not correctly handle bodies that don't respond to `#each`.

Correct handling of streaming body in `Rack::Response`.

---

CHANGELOG.md
lib/rack/request.rb

Remove deprecated Rack::Request::SCHEME_WHITELIST

---

lib/rack/request.rb
test/spec_request.rb

Tighten up IPv6 parsing rules using regexp extracted from resolv in stdlib,
simplified to avoid creating additional groups.
Tighten up hostname matching to graphical characters, except square brackets
(so it doesn't overlap with IPv6 parsing).
Avoid unnecessary IPv4 matching, since anything that matches as an IPv4
address would match as a hostname.
Remove unnecessary named group creation.
Don't allow trailing newlines in host names.
Fixes #1607
Co-authored-by: Pieter van de Bruggen <pvande@gmail.com>

Tighten authority matching

---

CHANGELOG.md
lib/rack/mock.rb
lib/rack/utils.rb
test/spec_response.rb

Fixes https://github.com/rack/rack/issues/1848

Use lower case normalisation for cookie attributes.

---

CHANGELOG.md

Sorry, another PR with a few more improvements that I botched in the "resolve conflicts" web interface :p
I also moved around the SPEC changes to try and prioritise things which seem more important first.

More improvements to changelog.

---

.github/workflows/development.yml
Gemfile
test/psych_fix.rb
test/spec_mock.rb
test/testrequest.rb

- partially backporting 2833813bd7f2a1872831d83cc9a0bb60f7d94fdd

Add Ruby 2.3 compatibility for tests, add Ruby 2.3 to CI.

---

lib/rack/deflater.rb
lib/rack/lint.rb
lib/rack/request.rb
lib/rack/server.rb
lib/rack/utils.rb
test/helper.rb
test/spec_deflater.rb
test/spec_lint.rb
test/spec_request.rb
test/spec_response.rb
test/spec_server.rb
test/spec_utils.rb

Also fix bugs, simplify code, and remove dead code noticed in coverage testing.
See individual commits for changes to each file.
Before:
```
3311 relevant lines, 3243 lines covered and 68 lines missed. ( 97.95% )
1140 total branches, 1021 branches covered and 119 branches missed. ( 89.56% )
```
After:
```
3286 relevant lines, 3282 lines covered and 4 lines missed. ( 99.88% )
1114 total branches, 1067 branches covered and 47 branches missed. ( 95.78% )
```
I plan to finish adding coverage testing next week, but it's probably best to get
these changes reviewed and committed before then.

Significantly improve test coverage

---

SPEC.rdoc
lib/rack/lint.rb

For readability, I fixed some formatting and wording
and also fixed the link to PEP 333 to match what Python
uses

Improve formatting and consistency

---

CHANGELOG.md

Or `git cherry-pick 925a4a6599ab26b4f3455b525393fe155d443655` https://github.com/rack/rack/commit/925a4a6599ab26b4f3455b525393fe155d443655

Copy missing v2.2.3.1 to main branch CHANGELOG

---

CHANGELOG.md
lib/rack/etag.rb
test/spec_etag.rb

https://github.com/rails/sprockets/issues/746#issuecomment-1168459287

Better support for case insensitive headers.

---

CHANGELOG.md

I had missed this note in there so I figured I might as well add the link to the PR number

Link PR #1748 in CHANGELOG

---

lib/rack/builder.rb

Found a typo while reading through doc.

Fix typo `interactively`

---

SPEC.rdoc
lib/rack/lint.rb

Clarify and validate `body.close` usage.
https://github.com/rack/rack/pull/1932

Clarify the life cycle of body and the requirement to call `close`.

---

UPGRADE-GUIDE.md

Add information on using Rack::Headers to the upgrade guide

---

UPGRADE-GUIDE.md

It seems to me that described at #1975 is not well documented.

fix: describe module autoloading in config.ru

---

CHANGELOG.md
lib/rack/method_override.rb
test/spec_method_override.rb

See discussion at https://github.com/jeremyevans/roda/discussions/291

Do not look for override method if there is no form/parseable data

---

.github/workflows/development.yml
test/spec_mock.rb

* Don't update to latest rubygems.
* Test on Ruby v3.2.

Update tests to work on latest Rubies. (#1999)

---

.mailmap

This is not extensive, but it's the best I could do in the time I had and the priorities for extracting gems. I believe we should continue to improve it.

Introduce mailmap for accurate git log and other commands.

---

CHANGELOG.md

https://github.com/rack/rack/commit/1bd0f1597d8f4a90d47115f3e156a8ce7870c9c8

Add JS MIME type change to CHANGELOG

---

lib/rack/multipart/parser.rb
test/spec_multipart.rb

Close https://github.com/rack/rack/issues/1968

Limit file extension length of multipart tempfiles

---

lib/rack/multipart/parser.rb
test/spec_multipart.rb

Not strictly necessary, but this limits the damage in pathological cases.  These limits are probably already too generous, we could probably get by with 8 params and 1024 bytes.  One of tests uses more than 1024 bytes, though.  Still, it seems unlikely any legitimate requests would exceed these limits.  We could make the limits configurable via an accessor method, if desired.

Limit max size and number of parameters parsed for Content-Disposition

---

CHANGELOG.md

Update CHANGELOG for 3.0.8 (3-0-stable)

---

CHANGELOG.md

Update CHANGELOG for 3.0.8

---

lib/rack/headers.rb

Some entries in this list are the similar entries with different case, but this is the exact same entry twice.

Remove duplicate X-Frame-Options

---

CHANGELOG.md

Update CHANGELOG for 2.2.8

---

CHANGELOG.md

I didn't know how account link works 🙏

Add link to account name in CHANGELOG.md

---

.github/workflows/test.yaml

This PR adds Ruby 3.3 to CI matrix

Add Ruby 3.3 to CI matrix

---

SPEC.rdoc
lib/rack/lint.rb
test/spec_lint.rb

See https://github.com/rack/rack/issues/2141#issuecomment-1919304906 for context.

Remove HTTP_VERSION validation from `Rack::Lint`.

---

test/spec_multipart.rb

This commit updates the spec description for improved grammar and consistency with the surrounding spec descriptions.

Refactored multipart_spec.rb to improve readability and consistency.

---

lib/rack/response.rb

Updates deprecation message to specify how to fix the deprecation.

Update deprecation message

---

CHANGELOG.md
lib/rack/body_proxy.rb
test/spec_body_proxy.rb

See conversation in https://github.com/rack/rack/pull/2062#issuecomment-2102291754

Backport #2062 to 3-0-stable

---

test/spec_request.rb
test/spec_utils.rb

Simplifies the tests a little.

Simplify warning capture in tests.

---

CHANGELOG.md
lib/rack/request.rb
test/spec_request.rb

For more context, see <https://github.com/rack/rack/pull/2183#pullrequestreview-2091002828>

Remove `Rack::Request#values_at`.

---

CHANGELOG.md

Reference the correct pull request.

Fix PR reference in CHANGELOG

---

CHANGELOG.md
lib/rack/mock_response.rb
test/spec_mock_response.rb

Fix handling of empty cookies in MockResponse

---

CHANGELOG.md

Close https://github.com/rack/rack/issues/2215
[ci skip]

Add 3.1.3 to CHANGELOG

---

CHANGELOG.md

I did not see https://github.com/rack/rack/pull/2214 mentioned in the changelog

Note "Allow empty PATH_INFO" in CHANGELOG

---

lib/rack/mock_request.rb
lib/rack/multipart/parser.rb
test/spec_mock_request.rb
test/spec_multipart.rb

May want to release 3.1.7 with these fixes and #2234

Backport a couple regression fixes to 3.1-stable

---

.github/workflows/test-external.yaml

Trying the suggestion from here <https://github.com/actions/runner-images/issues/10215#issuecomment-2229079104>.

Fix permissions.

---

lib/rack/lint.rb
lib/rack/utils.rb

Backport #2242 to 3-1-stable. Forgot to open this

[3-1-stable] Resolve deprecation warnings about uri `DEFAULT_PARSER` (#2242)

---

.github/workflows/test-external.yaml

Drop v3.1 as Rails head no longer supports it.

---

SPEC.rdoc
lib/rack/lint.rb

Something is wrong with the formatting. I might move it up to be with the other definitions too.

Fix broken paragraph.

---

UPGRADE-GUIDE.md

Following the discussion in https://github.com/rack/rack/issues/2128 about nested parameters parsing change in rack 3, here is a suggestion PR to mention it in the upgrade guide.

Add note about nested parameters parsing change in rack 3

---

lib/rack.rb

Logger file doesn't seem to be present.

Logger file doesn't seem to be present

---

lib/rack/lint.rb
test/spec_lint.rb

Replace it with `Rack::Lint.new(valid_app)` and enforce this in `Rack::Lint#initialize(app)`.

`Rack::Lint.new(nil)` is invalid.

---

SPEC.rdoc
lib/rack/lint.rb
test/spec_lint.rb

As part of <https://github.com/rack/rack/pull/2256> I would like to move this check earlier. It is better to validate generally before validating specifically, so I think this is a technical improvement too.

Move key/value check earlier.

---

CHANGELOG.md
SPEC.rdoc
lib/rack/lint.rb

See <https://github.com/rack/rack/issues/2293> for context.

Fix specification of `SERVER_PORT`.

---

SPEC.rdoc
lib/rack/lint.rb

It's fine to have a class be a rack application, as long as the class responds to call.

Remove incorrect text in SPEC

---

CHANGELOG.md
SPEC.rdoc
lib/rack/lint.rb
test/spec_lint.rb

Better validation of `HTTP_HOST` and `SERVER_NAME` according to RFCs.

---

lib/rack/mock.rb

Change CGI::Cookie.new to Cookie.new

---

lib/rack/media_type.rb
test/spec_media_type.rb

Backports https://github.com/rack/rack/pull/2263 to `2-2-stable`
for https://github.com/rack/rack/issues/2250#issuecomment-2922475996

Backport #2263 to v2.2, fix: malformed charset param

---

CHANGELOG.md

References: https://github.com/rack/rack/issues/2326

CHANGELOG.md: 3.1.14 breaking change

---

CHANGELOG.md
lib/rack/conditional_get.rb

Directly close the body.

---

lib/rack/lint.rb

This is a follow-up PR to avoid doing so many hash lookups and implement the proposed change in syntax as discussed here: <https://github.com/rack/rack/pull/2316#discussion_r2241223287>.
There is no behavioural change (and I'm open to other improvements).
- Move the `if script_name == "/"` check inside the `if script_name` block. If it's known to be `nil`, there is no point doing the check.
- Extract `path_info = env[PATH_INFO]` for both the `nil?`/`empty?` check, and the subsequent format check.

Tidy up checks for `script_name`, `path_info`.

---

CHANGELOG.md
lib/rack/head.rb
test/spec_head.rb

Directly close the body in Rack::Head

---

CHANGELOG.md
README.md
lib/rack/version.rb

Rack 3.2 is primarily a **maintenance and cleanup release** focused on improving specification compliance, performance, and code quality. 
**Key characteristics:**
- **SPEC improvements** - Updates to the Rack specification for better HTTP standards compliance.
- **Performance optimizations** - Several enhancements to request processing and caching behavior.
- **Breaking changes** - Removal of deprecated features including `Rack::Logger`, `Rack::Request#values_at`, and `CGI::Cookie` support.
- **Bug fixes** - Various fixes for edge cases in multipart handling, IPv6 support, and middleware behavior.
- **New conveniences** - A few developer-friendly additions like custom query parsers and raw form data access.
- **Documentation improvements** - A significant effort went into improving the …

Release 3.2
